name: Update Data

on:
  schedule:
    - cron: "0 0 15 * *"  #run every 15th
  workflow_dispatch: 

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
    #step1 repository
    - name: Checkout repository
      uses: actions/checkout@v3

    #step2 set up python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use a compatible Python version

    #step3 install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #step4 get data
    - name: Grab and process BLS data
      run: python grab_and_process_data.py

    #step5 commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add bls_data.csv
        git commit -m "Update BLS data (automated)" || echo "No changes to commit"
        git push
