[theme]
primaryColor="#FF69B4"  # Hot pink for accents and interactive widgets 💖
backgroundColor="#F8F9FA"  # Off-white background
secondaryBackgroundColor="#DADADA"  # Plain grey for sidebar and widgets
textColor="#1C1C1C"  # Very dark grey, almost black
font="sans serif"  # Clean and modern sans-serif font
